networks:
  shared:
    driver: bridge

services:

  mgoblog_ingestion_pipeline:
    build:
      dockerfile: ./pipelines/mgoblog_ingestion_pipeline/Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - .env
    profiles:
      - mgoblog_ingestion_pipeline
    networks:
      - shared

  all_tests:
    build:
      dockerfile: tests.Dockerfile
    env_file:
      - .env
    profiles:
      - all_tests
    networks:
      - shared

  user_query_api:
    build:
      dockerfile: ./pipelines/user_query/Dockerfile
    ports:
      - "5005:80"
    env_file:
      - .env
    environment:
      - FLASK_APP=user_query.py
      - FLASK_ENV=development
    profiles:
      - user_query_api
    networks:
      - shared

  elt_db:
    build:
      dockerfile: ./src/pipeline_framework/elt_db/Dockerfile
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./src/pipeline_framework/elt_db/data:/data/db
    profiles:
      - elt_db
    networks:
      - shared

  vector_db:
    build:
      dockerfile: ./src/pipeline_framework/vector_db/Dockerfile
    ports:
      - 6333:6333
    volumes:
      - ./src/pipeline_framework/vector_db/db_path:/db_path
      - ./src/pipeline_framework/vector_db/index_data:/chroma/.chroma/index
    profiles:
      - vector_db
    networks:
      - shared