networks:
  shared:
    driver: bridge

services:
  test_mgoblog_data:
    build:
      dockerfile: tests.Dockerfile
    depends_on:
      - elt_db
      - vector_db
    ports:
      - "9000:8080"
    env_file:
      - .env
    profiles:
      - test_mgoblog_data
    networks:
      - shared

  elt_db:
    build:
      dockerfile: ./src/pipeline_framework/elt_db/Dockerfile
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./src/pipeline_framework/elt_db/data:/data/db
    networks:
      - shared

  vector_db:
    build:
      dockerfile: ./src/pipeline_framework/vector_db/Dockerfile
    ports:
      - 6333:6333
    volumes:
      - ./src/pipeline_framework/vector_db/db_path:/db_path
      - ./src/pipeline_framework/vector_db/index_data:/chroma/.chroma/index
    networks:
      - shared

  scrape_mgoblog_data:
    build:
      dockerfile: ./src/ingest_mgoblog_data/scrape_mgoblog_data/Dockerfile
    depends_on:
      - elt_db
    ports:
      - "9000:8080"
    profiles:
      - scrape_mgoblog_data
    networks:
      - shared

  ingest_mgoblog_data:
    build:
      dockerfile: ./src/ingest_mgoblog_data/Dockerfile
    depends_on:
      - elt_db
    ports:
      - "9000:8080"
    profiles:
      - ingest_mgoblog_data
    networks:
      - shared