networks:
  shared:
    driver: bridge

services:
  test_chatmgoblog:
    build:
      dockerfile: tests.Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - .env
    profiles:
      - test_chatmgoblog

  test_ingest_mgoblog_data:
    build:
      dockerfile: ./src/ingest_mgoblog_data/tests/tests.Dockerfile
    depends_on:
      - test_elt_db
    ports:
      - "9000:8080"
    env_file:
      - .env
    profiles:
      - test_ingest_mgoblog_data
    networks:
      - shared

  test_embed:
    build:
      dockerfile: ./src/embed/tests/tests.Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - .env
    profiles:
      - test_embed

  test_content_index:
    build:
      dockerfile: ./src/content_index/tests/tests.Dockerfile
    depends_on:
      - test_vector_db
    ports:
      - "9000:8080"
    env_file:
      - .env
    profiles:
      - test_content_index
    networks:
      - shared

  elt_db:
    build:
      dockerfile: ./src/pipeline_framework/elt_db/Dockerfile
    ports:
      - 27017:27017
    env_file:
      - .env
    profiles:
      - elt_db
    volumes:
      - ./src/pipeline_framework/elt_db/data:/data/db
    networks:
      - shared

  test_elt_db:
    build:
      dockerfile: ./src/pipeline_framework/elt_db/Dockerfile
    ports:
      - 27017:27017
    env_file:
      - .env
    profiles:
      - test_elt_db
    volumes:
      - ./src/pipeline_framework/test_elt_db/data:/data/db
    networks:
      - shared

  vector_db:
    build:
      dockerfile: ./src/pipeline_framework/vector_db/Dockerfile
    ports:
      - 6333:6333
    volumes:
      - ./src/pipeline_framework/vector_db/db_path:/db_path
      - ./src/pipeline_framework/vector_db/index_data:/chroma/.chroma/index
    profiles:
      - vector_db
    networks:
      - shared

  test_vector_db:
    build:
      dockerfile: ./src/pipeline_framework/vector_db/Dockerfile
    ports:
      - 6333:6333
    volumes:
      - ./src/pipeline_framework/test_vector_db/db_path:/db_path
      - ./src/pipeline_framework/test_vector_db/index_data:/chroma/.chroma/index
    profiles:
      - test_vector_db
    networks:
      - shared

  index_content:
    build:
      dockerfile: ./src/index_content/index_content/Dockerfile
    depends_on:
      - elt_db
      - vector_db
    ports:
      - "9000:8080"
    profiles:
      - index_content
    networks:
      - shared